### ISSUE TITLE
Scan/save to local machine and upload to database later

### ISSUE THREAD

**Issue by MacBoyPro98** [MacBoyPro98/ChapelScan#8]
Requested that to keep network traffic low, we scan to a file on the desktop and then upload to the database at a later time.

**Todo**
- [x] Create a page to upload to the database
- [x] Find a way to save to local desktop from website
- [x] Save as a .csv file
